/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as MapRouteImport } from './routes/map'
import { Route as MonasteriesIndexRouteImport } from './routes/monasteries.index'
import { Route as MonasteriesSlugRouteImport } from './routes/monasteries.$slug'
import { Route as TourSlugRouteImport } from './routes/tour.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MonasteriesIndexRoute = MonasteriesIndexRouteImport.update({
  id: '/monasteries/',
  path: '/monasteries/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonasteriesSlugRoute = MonasteriesSlugRouteImport.update({
  id: '/monasteries/$slug',
  path: '/monasteries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TourSlugRoute = TourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archives': typeof ArchivesRoute
  '/calendar': typeof CalendarRoute
  '/map': typeof MapRoute
  '/monasteries/$slug': typeof MonasteriesSlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/monasteries/': typeof MonasteriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archives': typeof ArchivesRoute
  '/calendar': typeof CalendarRoute
  '/map': typeof MapRoute
  '/monasteries/$slug': typeof MonasteriesSlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/monasteries': typeof MonasteriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archives': typeof ArchivesRoute
  '/calendar': typeof CalendarRoute
  '/map': typeof MapRoute
  '/monasteries/$slug': typeof MonasteriesSlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/monasteries/': typeof MonasteriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archives'
    | '/calendar'
    | '/map'
    | '/monasteries/$slug'
    | '/tour/$slug'
    | '/monasteries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archives'
    | '/calendar'
    | '/map'
    | '/monasteries/$slug'
    | '/tour/$slug'
    | '/monasteries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archives'
    | '/calendar'
    | '/map'
    | '/monasteries/$slug'
    | '/tour/$slug'
    | '/monasteries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchivesRoute: typeof ArchivesRoute
  CalendarRoute: typeof CalendarRoute
  MapRoute: typeof MapRoute
  MonasteriesSlugRoute: typeof MonasteriesSlugRoute
  TourSlugRoute: typeof TourSlugRoute
  MonasteriesIndexRoute: typeof MonasteriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monasteries/': {
      id: '/monasteries/'
      path: '/monasteries'
      fullPath: '/monasteries/'
      preLoaderRoute: typeof MonasteriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monasteries/$slug': {
      id: '/monasteries/$slug'
      path: '/monasteries/$slug'
      fullPath: '/monasteries/$slug'
      preLoaderRoute: typeof MonasteriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$slug': {
      id: '/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchivesRoute: ArchivesRoute,
  CalendarRoute: CalendarRoute,
  MapRoute: MapRoute,
  MonasteriesSlugRoute: MonasteriesSlugRoute,
  TourSlugRoute: TourSlugRoute,
  MonasteriesIndexRoute: MonasteriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
